#ifndef _USER_SMARTPLUG_H
#define _USER_SMARTPLUG_H

#define GPIO_VALUE_0 0
#define GPIO_VALUE_1 1

/* LED */
#define SMARTPLUG_POWER_LED_GPIO     12

#define SMARTPLUG_WIFI_LED_GPIO      13


/* KEY */
#define SMARTPLUG_KEY_NUM          2

#define SMARTPLUG_KEY1_IO_MUX       PERIPHS_IO_MUX_MTMS_U
#define SMARTPLUG_KEY1_IO_GPIO      14
#define SMARTPLUG_KEY1_IO_FUNC      FUNC_GPIO14

#define SMARTPLUG_KEY2_IO_MUX       PERIPHS_IO_MUX_GPIO4_U
#define SMARTPLUG_KEY2_IO_GPIO      4
#define SMARTPLUG_KEY2_IO_FUNC      FUNC_GPIO4

/* CONTROL */
#define SMARTPLUG_CTRL_IO_MUX     PERIPHS_IO_MUX_MTDO_U
#define SMARTPLUG_CTRL_IO_GPIO    15
#define SMARTPLUG_CTRL_IO_FUNC    FUNC_GPIO15

/* PATH */
#define SMARTPLUG_POWER                   "OnOff_Power"

#endif /*_USER_SMARTPLUG_H */
