#ifndef __WELCOME_H__
#define __WELCOME_H__

#define WELCOME_DIS_LEAVE_DIS   0
#define WELCOME_ENA_LEAVE_DIS    1
#define WELCOME_DIS_LEAVE_ENA   2
#define WELCOME_ENA_LEAVE_ENA  3

enum {
    WELCOME_ACTION_WELCOME_ENABLE_BIT = 0,
    WELCOME_ACTION_LEAVE_ENABLE_BIT
};

#define WELCOME_REQUEST_TIMEOUT    (30*60)      /* 30 min */
#define WELCOME_PING_TIMEOUT    (10*60)      /* 10 min */
 
#define DHCP_CLIENT_IP_ADDRESS_OFFSET  12
#define DHCP_CLIENT_MAC_ADDRESS_OFFSET 28
#define DHCP_OPTION_OFFSET             0xF0
#define DHCP_OPTION_MESSAGE_TYPE_OFFSET 0xF0

#define WELCOME_MAX_PING_COUNT  4

#endif /* __WELCOME_H__ */
